### PR TITLE
Server to client state update

### PR DESCRIPTION
**Pull request by mrboisvert**
Created object state classes based on the class diagram.

Created physics_engine methods for adding object states to the game space, removing objects, stepping forward in time.

Created unit tests for the new physics_engine methods.

Added methods and message types to the Message class for sending agent and projectile states to the clients.

### CODE REVIEW

**Comment by mayshukla** [comment]
Mostly looks good to me.

Any ideas as to how we're gonna generate IDs for ObjectStates? I have a few ideas:
1. Add a method to Game called `getID()` which just returns a new incremental number each time. It kinda makes sense to generate IDs in the Game class since IDs only need to be unique within one game
2. Add a static method in ObjectState that sets the ID to a new incremental number each time the constructor is called. This is convenient but we don't actually need that many unique IDs.
3. Do 1 or 2 but with UUIDs instead of just incremental integers

Let me know what you think

**Comment by mayshukla** [comment]
Another small thing: in the Message class, instead of having to use `to_json_array` for AGENT_STATES and PROJECTILE_STATES messages, could you modify `to_json` to check if `data` is a list and then call `to_json_array`? That way, every message type can be converted to json using `to_json`

**Comment by mrboisvert** [comment]
I'm kind of leaning towards the first option where the IDs are only unique per game with simple incrementing IDs. I can see the merits of the other options though. I don't think it will make a huge difference in the end.

Yeah I will make that change for the to_json  method, that should be cleaner. I meant to bring that up in the meeting.

**Review by mayshukla — APPROVED** [review]

**Comment by mayshukla** [comment]
> I'm kind of leaning towards the first option where the IDs are only unique per game with simple incrementing IDs. I can see the merits of the other options though. I don't think it will make a huge difference in the end.
> 
> Yeah I will make that change for the to_json method, that should be cleaner. I meant to bring that up in the meeting.

Sweet. I'd say you're good to merge this once you make that change.

**Pull request merged**
